import { ApiError } from '../utils/api-error.js'; import * as repository from '../repositories/task.repository.js'; import { createNotification } from './notification.service.js'; import type { PaginatedTasks, PublicTask, TaskInput, TaskListQuery } from '../types/task.types.js';
const publicTask=(x: Awaited<ReturnType<typeof repository.findTask>>):PublicTask=>{if(!x)throw ApiError.notFound('Task not found');return {id:x.id,title:x.title,description:x.description,assignee:{id:x.assigned_to,firstName:x.assignee_first_name,lastName:x.assignee_last_name,email:x.assignee_email,avatar:x.assignee_avatar},company:x.related_company?{id:x.related_company,name:x.company_name??''}:null,contact:x.related_contact?{id:x.related_contact,firstName:x.contact_first_name??'',lastName:x.contact_last_name??''}:null,lead:x.related_lead?{id:x.related_lead}:null,dueDate:x.due_date,priority:x.priority,status:x.status,createdAt:x.created_at,updatedAt:x.updated_at};};
async function validate(x:TaskInput){for(const [key,table] of [['assignedTo','users'],['relatedCompany','companies'],['relatedContact','contacts'],['relatedLead','leads']] as const){const value=x[key];if(value!==undefined&&value!==null&&!(await repository.exists(table,value)))throw ApiError.badRequest(`The provided ${key} does not exist`);}}
export async function getTasks(q:TaskListQuery):Promise<PaginatedTasks>{const r=await repository.listTasks(q);return {items:r.rows.map((x)=>publicTask(x)),total:r.total,page:q.page,limit:q.limit,totalPages:Math.ceil(r.total/q.limit)};}
export async function getTask(id:number){return publicTask(await repository.findTask(id));}
async function notifyAssignment(taskId:number,userId:number,actorId?:number){if(userId===actorId)return;try{await createNotification(userId,{type:'TASK_ASSIGNED',title:'Nouvelle tâche assignée',message:'Une nouvelle tâche vous a été assignée.',entityType:'task',entityId:taskId});}catch{console.error('Notification creation failed',{event:'task_assigned',taskId});}}
export async function createTask(x:TaskInput,actorId?:number){if(!x.title||!x.assignedTo)throw ApiError.badRequest('title and assignedTo are required');await validate(x);const task=publicTask(await repository.findTask(await repository.createTask(x as Required<Pick<TaskInput,'title'|'assignedTo'>> & TaskInput)));await notifyAssignment(task.id,task.assignee.id,actorId);return task;}
export async function updateTask(id:number,x:TaskInput,actorId?:number){const previous=await getTask(id);await validate(x);await repository.updateTask(id,x);const task=await getTask(id);if(x.assignedTo!==undefined&&x.assignedTo!==previous.assignee.id)await notifyAssignment(task.id,x.assignedTo,actorId);return task;}
export async function updateTaskStatus(id:number,status:NonNullable<TaskInput['status']>){return updateTask(id,{status});}
export async function deleteTask(id:number){await getTask(id);await repository.softDeleteTask(id);}
