import type { ResultSetHeader, RowDataPacket } from 'mysql2'; import { pool } from '../config/database.js'; import type { TaskInput, TaskListQuery, TaskPriority, TaskStatus } from '../types/task.types.js';
interface Row extends RowDataPacket { id: number; title: string; description: string | null; assigned_to: number; assignee_first_name: string; assignee_last_name: string; assignee_email: string; assignee_avatar: string | null; related_company: number | null; company_name: string | null; related_contact: number | null; contact_first_name: string | null; contact_last_name: string | null; related_lead: number | null; due_date: string | null; priority: TaskPriority; status: TaskStatus; created_at: Date; updated_at: Date }
const select = `SELECT t.id,t.title,t.description,t.assigned_to,u.first_name assignee_first_name,u.last_name assignee_last_name,u.email assignee_email,u.avatar assignee_avatar,t.related_company,c.name company_name,t.related_contact,co.first_name contact_first_name,co.last_name contact_last_name,t.related_lead,t.due_date,t.priority,t.status,t.created_at,t.updated_at FROM tasks t INNER JOIN users u ON u.id=t.assigned_to AND u.deleted_at IS NULL LEFT JOIN companies c ON c.id=t.related_company AND c.deleted_at IS NULL LEFT JOIN contacts co ON co.id=t.related_contact AND co.deleted_at IS NULL LEFT JOIN leads l ON l.id=t.related_lead AND l.deleted_at IS NULL`;
const sortable: Record<string,string> = { title:'t.title', due_date:'t.due_date', priority:'t.priority', status:'t.status', created_at:'t.created_at', updated_at:'t.updated_at' };
export async function findTask(id: number) { const [rows] = await pool.query<Row[]>(`${select} WHERE t.id=? AND t.deleted_at IS NULL`, [id]); return rows[0] ?? null; }
export async function listTasks(q: TaskListQuery) { const conditions=['t.deleted_at IS NULL']; const params: Array<string|number> = []; if(q.search){const x=`%${q.search}%`; params.push(x,x,x,x,x); conditions.push('(t.title LIKE ? OR t.description LIKE ? OR c.name LIKE ? OR co.first_name LIKE ? OR co.last_name LIKE ?)');} if(q.status){params.push(q.status);conditions.push('t.status=?');} if(q.priority){params.push(q.priority);conditions.push('t.priority=?');} if(q.assignee){params.push(q.assignee);conditions.push('t.assigned_to=?');} if(q.dueDate){params.push(q.dueDate);conditions.push('t.due_date=?');} if(q.entityType&&q.entityId){const map={company:'related_company',contact:'related_contact',lead:'related_lead'};params.push(q.entityId);conditions.push(`t.${map[q.entityType]}=?`);} const where=`WHERE ${conditions.join(' AND ')}`; const [count]=await pool.query<Array<{total:number}> & RowDataPacket[]>(`SELECT COUNT(*) total FROM tasks t INNER JOIN users u ON u.id=t.assigned_to AND u.deleted_at IS NULL LEFT JOIN companies c ON c.id=t.related_company AND c.deleted_at IS NULL LEFT JOIN contacts co ON co.id=t.related_contact AND co.deleted_at IS NULL ${where}`,params); const col=sortable[q.sortBy]??'t.created_at'; const [rows]=await pool.query<Row[]>(`${select} ${where} ORDER BY ${col} ${q.order==='asc'?'ASC':'DESC'} LIMIT ? OFFSET ?`,[...params,q.limit,(q.page-1)*q.limit]); return { rows,total:count[0]?.total??0 }; }
export async function createTask(x: Required<Pick<TaskInput,'title'|'assignedTo'>> & TaskInput) { const [r]=await pool.execute<ResultSetHeader>('INSERT INTO tasks (title,description,assigned_to,related_company,related_contact,related_lead,due_date,priority,status) VALUES (?,?,?,?,?,?,?,?,?)',[x.title,x.description??null,x.assignedTo,x.relatedCompany??null,x.relatedContact??null,x.relatedLead??null,x.dueDate??null,x.priority??'medium',x.status??'pending']); return r.insertId; }
export async function updateTask(id:number,x:TaskInput){const fields:string[]=[];const values:Array<string|number|null>=[]; const add=(k:string,v:string|number|null|undefined)=>{if(v!==undefined){fields.push(`${k}=?`);values.push(v);}};add('title',x.title);add('description',x.description);add('assigned_to',x.assignedTo);add('related_company',x.relatedCompany);add('related_contact',x.relatedContact);add('related_lead',x.relatedLead);add('due_date',x.dueDate);add('priority',x.priority);add('status',x.status);if(fields.length){values.push(id);await pool.execute(`UPDATE tasks SET ${fields.join(', ')} WHERE id=? AND deleted_at IS NULL`,values);}}
export async function softDeleteTask(id:number){await pool.execute('UPDATE tasks SET deleted_at=NOW() WHERE id=? AND deleted_at IS NULL',[id]);}
export async function exists(table:'users'|'companies'|'contacts'|'leads',id:number){const deleted=table==='users'||table==='companies'||table==='contacts'||table==='leads';const [rows]=await pool.query<RowDataPacket[]>(`SELECT id FROM ${table} WHERE id=?${deleted?' AND deleted_at IS NULL':''} LIMIT 1`,[id]);return rows.length>0;}
