import { useMemo, useState } from 'react';
import { Eye, Pencil, Plus, RefreshCw, Search, Target, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { Input } from '@/components/ui/Input';
import { Pagination } from '@/components/ui/Pagination';
import { Select } from '@/components/ui/Select';
import { useAuth } from '@/hooks/useAuth';
import { useNotifications } from '@/hooks/useNotifications';
import { formatCurrency } from '@/utils/formatCurrency';
import { useDebouncedValue } from '@/features/leads/hooks';
import { leadPermissionsForRole } from '@/features/leads/lib';
import { ConfirmOpportunityDialog, OpportunityDetailsDrawer, OpportunityFormModal } from '@/features/opportunities/components';
import { useCreateOpportunity, useDeleteOpportunity, useOpportunityCompanies, useOpportunityContacts, useOpportunityOptions, useOpportunityOwners, useOpportunities, useUpdateOpportunity } from '@/features/opportunities/hooks/useManagedOpportunities';
import type { CreateManagedOpportunityInput, ManagedOpportunitiesSortField, ManagedOpportunity, OpportunityStatus, UpdateManagedOpportunityInput } from '@/features/opportunities/types/opportunity-management.types';

const PAGE_SIZE = 10;
type Dialog = { kind: 'create' } | { kind: 'edit' | 'details' | 'delete'; opportunity: ManagedOpportunity } | null;
const badge = (status: OpportunityStatus) => ({ open: 'bg-accent-subtle text-accent', won: 'bg-success-subtle text-success-500', lost: 'bg-danger-subtle text-danger-400' }[status]);
const label = (status: OpportunityStatus) => ({ open: 'Ouverte', won: 'Gagnée', lost: 'Perdue' }[status]);
const money = (v: number) => formatCurrency(v);

export function OpportunitiesPage() {
  const { user } = useAuth(); const permissions = leadPermissionsForRole(user?.role ?? 'viewer'); const { success, error: notifyError } = useNotifications();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const debouncedSearch = useDebouncedValue(search, 300); const [status, setStatus] = useState(''); const [stage, setStage] = useState(''); const [ownerId, setOwnerId] = useState(''); const [companyId, setCompanyId] = useState(''); const [pipelineId, setPipelineId] = useState(''); const [sort, setSort] = useState<ManagedOpportunitiesSortField>('created_at'); const [order, setOrder] = useState<'asc' | 'desc'>('desc'); const [dialog, setDialog] = useState<Dialog>(null);
  const query = useMemo(() => ({ page, limit: PAGE_SIZE, ...(debouncedSearch.trim() ? { search: debouncedSearch.trim() } : {}), ...(status ? { status: status as OpportunityStatus } : {}), ...(stage ? { stage: Number(stage) } : {}), ...(ownerId ? { ownerId: Number(ownerId) } : {}), ...(companyId ? { companyId: Number(companyId) } : {}), ...(pipelineId ? { pipelineId: Number(pipelineId) } : {}), sort, order }), [page, debouncedSearch, status, stage, ownerId, companyId, pipelineId, sort, order]);
  const list = useOpportunities(query); const options = useOpportunityOptions(); const owners = useOpportunityOwners(); const companies = useOpportunityCompanies(); const contacts = useOpportunityContacts(); const create = useCreateOpportunity(); const update = useUpdateOpportunity(); const remove = useDeleteOpportunity();
  const reset = () => { setSearch(''); setStatus(''); setStage(''); setOwnerId(''); setCompanyId(''); setPipelineId(''); setPage(1); }; const active = Boolean(debouncedSearch || status || stage || ownerId || companyId || pipelineId); const busy = create.isPending || update.isPending || remove.isPending;
  const submit = (input: CreateManagedOpportunityInput | UpdateManagedOpportunityInput) => { if (dialog?.kind === 'edit') update.mutate({ id: dialog.opportunity.id, input }, { onSuccess: () => { success('Opportunité mise à jour.'); setDialog(null); }, onError: (e) => notifyError(e.message) }); else create.mutate(input as CreateManagedOpportunityInput, { onSuccess: () => { success('Opportunité créée.'); setDialog(null); }, onError: (e) => notifyError(e.message) }); };
  return <div className="flex flex-col gap-5"><header className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-subtle text-accent"><Target className="h-5 w-5" /></div><div><h1 className="text-xl font-semibold text-text-primary">Opportunités</h1><p className="text-[13px] text-text-tertiary">Suivez vos ventes et leur progression.</p></div></div><span className="text-[12px] text-text-tertiary">{list.data?.total ?? 0} opportunité(s)</span></header>
    <section className="rounded-xl border border-border bg-surface p-3"><div className="flex flex-col gap-3 lg:flex-row"><Input className="flex-1" placeholder="Rechercher une entreprise ou un contact…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} leftIcon={<Search className="h-4 w-4" />} /><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => list.refetch()} loading={list.isLoading} leadingIcon={<RefreshCw className="h-4 w-4" />}>Actualiser</Button>{permissions.canCreate && <Button onClick={() => setDialog({ kind: 'create' })} leadingIcon={<Plus className="h-4 w-4" />}>Ajouter</Button>}</div></div><div className="mt-3 grid grid-cols-2 gap-2 border-t border-border pt-3 md:grid-cols-6"><Select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} options={[{ value: '', label: 'Tous statuts' }, { value: 'open', label: 'Ouvertes' }, { value: 'won', label: 'Gagnées' }, { value: 'lost', label: 'Perdues' }]} /><Select value={pipelineId} onChange={(e) => { setPipelineId(e.target.value); setStage(''); setPage(1); }} options={[{ value: '', label: 'Tous pipelines' }, ...(options.data?.pipelines ?? []).map((x) => ({ value: String(x.id), label: x.name }))]} /><Select value={stage} onChange={(e) => { setStage(e.target.value); setPage(1); }} options={[{ value: '', label: 'Toutes étapes' }, ...(options.data?.stages ?? []).filter((x) => !pipelineId || x.pipelineId === Number(pipelineId)).map((x) => ({ value: String(x.id), label: x.name }))]} /><Select value={companyId} onChange={(e) => { setCompanyId(e.target.value); setPage(1); }} options={[{ value: '', label: 'Toutes entreprises' }, ...(companies.data ?? []).map((x) => ({ value: String(x.id), label: x.name }))]} /><Select value={ownerId} onChange={(e) => { setOwnerId(e.target.value); setPage(1); }} options={[{ value: '', label: 'Tous responsables' }, ...(owners.data ?? []).map((x) => ({ value: String(x.id), label: `${x.firstName} ${x.lastName}` }))]} /><Select value={sort} onChange={(e) => { setSort(e.target.value as ManagedOpportunitiesSortField); setPage(1); }} options={[{ value: 'created_at', label: 'Créées le' }, { value: 'value', label: 'Valeur' }, { value: 'expected_close_date', label: 'Clôture' }, { value: 'probability', label: 'Probabilité' }]} /></div></section>
    {list.isLoading ? <div className="h-64 animate-pulse rounded-xl bg-skeleton" /> : list.isError ? <EmptyState icon={<Target />} title="Impossible de charger les opportunités" action={{ label: 'Réessayer', onClick: () => list.refetch() }} /> : !list.data?.items.length ? <EmptyState icon={<Target />} title={active ? 'Aucune opportunité trouvée' : 'Aucune opportunité'} description={active ? 'Aucun résultat ne correspond à vos filtres.' : 'Ajoutez votre première opportunité pour commencer.'} action={active ? { label: 'Réinitialiser', onClick: reset } : permissions.canCreate ? { label: 'Ajouter', onClick: () => setDialog({ kind: 'create' }) } : undefined} /> : <OpportunityTable opportunities={list.data.items} canEdit={permissions.canUpdate} canDelete={permissions.canDelete} onDetails={(opportunity) => setDialog({ kind: 'details', opportunity })} onEdit={(opportunity) => setDialog({ kind: 'edit', opportunity })} onDelete={(opportunity) => setDialog({ kind: 'delete', opportunity })} />}
    {list.data && list.data.totalPages > 1 && <div className="flex justify-end"><Pagination currentPage={list.data.page} totalPages={list.data.totalPages} onPageChange={setPage} /></div>}
    <OpportunityFormModal open={dialog?.kind === 'create' || dialog?.kind === 'edit'} opportunity={dialog?.kind === 'edit' ? dialog.opportunity : null} companies={companies.data ?? []} contacts={contacts.data ?? []} owners={owners.data ?? []} pipelines={options.data?.pipelines ?? []} stages={options.data?.stages ?? []} isSubmitting={busy} onClose={() => setDialog(null)} onSubmit={submit} /><OpportunityDetailsDrawer open={dialog?.kind === 'details'} opportunity={dialog?.kind === 'details' ? dialog.opportunity : null} onClose={() => setDialog(null)} /><ConfirmOpportunityDialog open={dialog?.kind === 'delete'} isLoading={remove.isPending} onClose={() => setDialog(null)} onConfirm={() => dialog?.kind === 'delete' && remove.mutate(dialog.opportunity.id, { onSuccess: () => { success('Opportunité supprimée.'); setDialog(null); }, onError: (e) => notifyError(e.message) })} />
  </div>;
}
function OpportunityTable({ opportunities, canEdit, canDelete, onDetails, onEdit, onDelete }: { opportunities: ManagedOpportunity[]; canEdit: boolean; canDelete: boolean; onDetails: (o: ManagedOpportunity) => void; onEdit: (o: ManagedOpportunity) => void; onDelete: (o: ManagedOpportunity) => void }) { return <div className="overflow-hidden rounded-xl border border-border bg-surface"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-[13px]"><thead className="bg-surface-secondary/60 text-[11px] uppercase text-text-tertiary"><tr>{['Entreprise', 'Contact', 'Étape', 'Valeur', 'Probabilité', 'Clôture', 'Responsable', 'Statut', ''].map((x) => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-border">{opportunities.map((o) => <tr key={o.id} className="hover:bg-surface-hover/50"><td className="px-4 py-3 font-medium">{o.company?.name ?? '—'}</td><td className="px-4 py-3">{o.contact ? `${o.contact.firstName} ${o.contact.lastName}` : '—'}</td><td className="px-4 py-3"><span className="rounded-md bg-background-tertiary px-2 py-1">{o.stage?.name ?? '—'}</span></td><td className="px-4 py-3">{money(o.amount)}</td><td className="px-4 py-3">{o.probability}%</td><td className="px-4 py-3">{o.expectedCloseDate ?? '—'}</td><td className="px-4 py-3">{o.owner.firstName} {o.owner.lastName}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${badge(o.status)}`}>{label(o.status)}</span></td><td className="px-4 py-3"><Actions o={o} canEdit={canEdit} canDelete={canDelete} onDetails={onDetails} onEdit={onEdit} onDelete={onDelete} /></td></tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{opportunities.map((o) => <article key={o.id} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between"><div><p className="font-semibold">{o.company?.name ?? `Opportunité #${o.id}`}</p><p className="text-[12px] text-text-tertiary">{o.stage?.name ?? '—'} · {money(o.amount)}</p></div><span className={`rounded-full px-2 py-1 text-[11px] ${badge(o.status)}`}>{label(o.status)}</span></div><div className="mt-3 border-t border-border pt-2"><Actions o={o} canEdit={canEdit} canDelete={canDelete} onDetails={onDetails} onEdit={onEdit} onDelete={onDelete} /></div></article>)}</div></div> }
function Actions({ o, canEdit, canDelete, onDetails, onEdit, onDelete }: { o: ManagedOpportunity; canEdit: boolean; canDelete: boolean; onDetails: (o: ManagedOpportunity) => void; onEdit: (o: ManagedOpportunity) => void; onDelete: (o: ManagedOpportunity) => void }) { return <div className="flex justify-end gap-1"><Button size="icon-sm" variant="ghost" aria-label="Détails" onClick={() => onDetails(o)}><Eye className="h-4 w-4" /></Button>{canEdit && <Button size="icon-sm" variant="ghost" aria-label="Modifier" onClick={() => onEdit(o)}><Pencil className="h-4 w-4" /></Button>}{canDelete && <Button size="icon-sm" variant="ghost" aria-label="Supprimer" onClick={() => onDelete(o)}><Trash2 className="h-4 w-4 text-danger-400" /></Button>}</div> }
