import { useMemo, useState } from 'react';
import { Filter, Plus, RefreshCw, Search, Target } from 'lucide-react';
import { Button } from '@/components/ui/Button'; import { EmptyState } from '@/components/ui/EmptyState'; import { Input } from '@/components/ui/Input'; import { Select } from '@/components/ui/Select';
import { useAuth } from '@/hooks/useAuth'; import { useNotifications } from '@/hooks/useNotifications'; import { usePipelineBoard, usePipelines, useMoveOpportunity } from '@/features/pipeline/hooks/usePipeline'; import { RealPipelineBoard } from '@/features/pipeline/components/RealPipelineBoard'; import { OpportunityDetailsDrawer } from '@/features/opportunities/components/OpportunityDetailsDrawer'; import type { ManagedOpportunity, OpportunityStatus } from '@/features/opportunities/types/opportunity-management.types';

export function PipelinePage() {
  const { user } = useAuth(); const { error } = useNotifications(); const pipelines = usePipelines(); const [selectedPipeline, setSelectedPipeline] = useState<number | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState<OpportunityStatus | ''>(''); const [selected, setSelected] = useState<ManagedOpportunity | null>(null);
  const pipelineId = selectedPipeline ?? pipelines.data?.[0]?.id ?? null; const query = useMemo(() => ({ ...(search.trim() ? { search: search.trim() } : {}), ...(status ? { status } : {}) }), [search, status]); const board = usePipelineBoard(pipelineId, query); const move = useMoveOpportunity(pipelineId, query); const canMove = ['admin', 'manager', 'sales'].includes(user?.role ?? '');
  return <div className="flex min-w-0 flex-col gap-4"><header className="flex flex-col gap-3 border-b border-border/80 pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-accent-subtle text-accent"><Target className="h-[18px] w-[18px]" /></div><div><h1 className="text-lg font-semibold tracking-tight text-text-primary">Pipeline</h1><p className="mt-0.5 text-[12px] text-text-tertiary">Visualisez et déplacez les opportunités en temps réel.</p></div></div><Button size="sm" disabled leadingIcon={<Plus className="h-4 w-4" />}>Nouvelle opportunité</Button></header>
    <section aria-label="Contrôles du pipeline" className="flex flex-col gap-2 rounded-xl border border-border bg-surface p-2.5 shadow-xs sm:flex-row sm:items-center"><Select className="sm:w-52" value={pipelineId ? String(pipelineId) : ''} onChange={(event) => setSelectedPipeline(Number(event.target.value))} options={(pipelines.data ?? []).map((pipeline) => ({ value: String(pipeline.id), label: pipeline.name }))} /><Input className="min-w-0 flex-1" placeholder="Rechercher une entreprise ou un contact…" value={search} onChange={(event) => setSearch(event.target.value)} leftIcon={<Search className="h-4 w-4" />} /><div className="flex gap-2"><Select className="w-32" aria-label="Filtrer par statut" value={status} onChange={(event) => setStatus(event.target.value as OpportunityStatus | '')} options={[{ value: '', label: 'Tous statuts' }, { value: 'open', label: 'Ouvertes' }, { value: 'won', label: 'Gagnées' }, { value: 'lost', label: 'Perdues' }]} /><Button variant="ghost" size="icon" aria-label="Actualiser le pipeline" onClick={() => board.refetch()} loading={board.isFetching}><RefreshCw className="h-4 w-4" /></Button></div></section>
    {pipelines.isLoading || board.isLoading ? <div className="h-[min(64vh,650px)] min-h-[360px] animate-pulse rounded-2xl bg-skeleton" /> : pipelines.isError || board.isError ? <EmptyState icon={<Target />} title="Impossible de charger le pipeline" action={{ label: 'Réessayer', onClick: () => board.refetch() }} /> : !pipelineId ? <EmptyState icon={<Target />} title="Aucun pipeline" description="Créez un pipeline pour commencer." /> : board.data && !board.data.stages.length ? <EmptyState icon={<Filter />} title="Aucune étape" description="Ce pipeline ne contient aucune étape." /> : board.data ? <RealPipelineBoard board={board.data} canMove={canMove} onCard={setSelected} onMove={(opportunityId, stageId) => move.mutate({ opportunityId, stageId }, { onError: (exception) => error(exception.message) })} /> : null}<OpportunityDetailsDrawer open={Boolean(selected)} opportunity={selected} onClose={() => setSelected(null)} /></div>;
}
