import { useEffect, useMemo } from 'react';
import { useForm } from 'react-hook-form';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { zodResolver } from '@/lib/zod-resolver';
import { opportunityFormSchema, type OpportunityFormValues } from '../schemas/opportunity-management.schema';
import type { CreateManagedOpportunityInput, ManagedOpportunity, OwnerOption, OpportunityOption, PipelineOption, StageOption, UpdateManagedOpportunityInput } from '../types/opportunity-management.types';
type SelectOption = { value: string; label: string };
interface Props { open: boolean; opportunity: ManagedOpportunity | null; companies: OpportunityOption[]; contacts: { id: number; firstName: string; lastName: string }[]; owners: OwnerOption[]; pipelines: PipelineOption[]; stages: StageOption[]; isSubmitting: boolean; onClose: () => void; onSubmit: (input: CreateManagedOpportunityInput | UpdateManagedOpportunityInput) => void }
export function OpportunityFormModal({ open, opportunity, companies, contacts, owners, pipelines, stages, isSubmitting, onClose, onSubmit }: Props) {
  const defaults = useMemo<OpportunityFormValues>(() => opportunity ? { companyId: String(opportunity.company?.id ?? ''), contactId: opportunity.contact ? String(opportunity.contact.id) : '', ownerId: String(opportunity.owner.id), pipelineId: String(opportunity.pipeline?.id ?? ''), stageId: String(opportunity.stage?.id ?? ''), probability: String(opportunity.probability), value: String(opportunity.amount), expectedCloseDate: opportunity.expectedCloseDate?.slice(0, 10) ?? '', status: opportunity.status } : { companyId: String(companies[0]?.id ?? ''), contactId: '', ownerId: String(owners[0]?.id ?? ''), pipelineId: String(pipelines[0]?.id ?? ''), stageId: '', probability: '', value: '', expectedCloseDate: '', status: 'open' }, [opportunity, companies, owners, pipelines]);
  const { register, handleSubmit, watch, reset, formState: { errors } } = useForm<OpportunityFormValues>({ resolver: zodResolver(opportunityFormSchema), defaultValues: defaults });
  useEffect(() => { if (open) reset(defaults); }, [open, defaults, reset]);
  const pipelineId = watch('pipelineId');
  const stageOptions: SelectOption[] = stages.filter((stage) => String(stage.pipelineId) === pipelineId).map((stage) => ({ value: String(stage.id), label: stage.name }));
  const submit = (v: OpportunityFormValues) => onSubmit({ companyId: Number(v.companyId), contactId: v.contactId ? Number(v.contactId) : null, ownerId: Number(v.ownerId), pipelineId: Number(v.pipelineId), stageId: Number(v.stageId), probability: v.probability === '' ? undefined : Number(v.probability), value: v.value === '' ? undefined : Number(v.value), expectedCloseDate: v.expectedCloseDate || null, status: v.status });
  return <Modal open={open} onClose={onClose} title={opportunity ? 'Modifier l’opportunité' : 'Ajouter une opportunité'} description="Les informations sont enregistrées dans LeadPro." size="lg"><form onSubmit={handleSubmit(submit)} className="flex flex-col gap-4"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Select label="Entreprise" options={companies.map((x) => ({ value: String(x.id), label: x.name }))} error={errors.companyId?.message} {...register('companyId')} /><Select label="Contact" options={[{ value: '', label: 'Aucun contact' }, ...contacts.map((x) => ({ value: String(x.id), label: `${x.firstName} ${x.lastName}` }))]} {...register('contactId')} /><Select label="Responsable" options={owners.map((x) => ({ value: String(x.id), label: `${x.firstName} ${x.lastName}` }))} error={errors.ownerId?.message} {...register('ownerId')} /><Select label="Pipeline" options={pipelines.map((x) => ({ value: String(x.id), label: x.name }))} error={errors.pipelineId?.message} {...register('pipelineId')} /><Select label="Étape" options={stageOptions} error={errors.stageId?.message} {...register('stageId')} /><Select label="Statut" options={[{ value: 'open', label: 'Ouverte' }, { value: 'won', label: 'Gagnée' }, { value: 'lost', label: 'Perdue' }]} {...register('status')} /><Input label="Valeur" type="number" min="0" step="0.01" error={errors.value?.message} {...register('value')} /><Input label="Probabilité (%)" type="number" min="0" max="100" step="0.01" error={errors.probability?.message} {...register('probability')} /><Input label="Date de clôture prévue" type="date" {...register('expectedCloseDate')} /></div><div className="flex justify-end gap-2 border-t border-border pt-4"><Button type="button" variant="ghost" onClick={onClose}>Annuler</Button><Button type="submit" loading={isSubmitting}>{opportunity ? 'Enregistrer' : 'Créer'}</Button></div></form></Modal>;
}
