import { useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, closestCorners, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent, type DragOverEvent } from '@dnd-kit/core';
import { CalendarDays, CircleDollarSign, FilePlus2, GripVertical, UserRound } from 'lucide-react';
import { motion } from 'framer-motion';
import { formatCurrency } from '@/utils/formatCurrency';
import { cn } from '@/lib/cn';
import type { ManagedOpportunity } from '@/features/opportunities/types/opportunity-management.types';
import type { PipelineBoardData, PipelineStage } from '../types/pipeline-api.types';

function Card({ opportunity, draggable, dragging, onClick }: { opportunity: ManagedOpportunity; draggable: boolean; dragging: boolean; onClick: () => void }) {
  const drag = useDraggable({ id: `opportunity:${opportunity.id}`, disabled: !draggable });
  return <motion.article ref={drag.setNodeRef} {...drag.listeners} {...drag.attributes} style={{ transform: drag.transform ? `translate3d(${drag.transform.x}px, ${drag.transform.y}px, 0)` : undefined }} onClick={onClick} whileHover={!dragging ? { y: -1 } : undefined} className={cn('group relative cursor-pointer rounded-xl border bg-surface p-3 shadow-xs transition-[border,box-shadow,opacity,transform] duration-150 focus-within:ring-2 focus-within:ring-accent/30', dragging ? 'z-20 scale-[1.025] border-accent/40 opacity-95 shadow-xl' : 'border-border hover:border-border-hover hover:shadow-md')}>
    <div className="flex items-start gap-2"><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-text-primary">Opportunity #{opportunity.id}</p><p className="mt-1 truncate text-[12px] font-medium text-text-secondary">{opportunity.company?.name ?? 'Entreprise non renseignée'}</p>{opportunity.contact && <p className="mt-0.5 truncate text-[11px] text-text-tertiary">{opportunity.contact.firstName} {opportunity.contact.lastName}</p>}</div>{draggable && <span className="mt-0.5 rounded-md p-0.5 text-text-tertiary opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100"><GripVertical className="h-4 w-4" aria-label="Déplacer l'opportunité" /></span>}</div>
    <div className="mt-3 flex items-center justify-between border-t border-border/70 pt-2.5"><span className="inline-flex items-center gap-1 text-[13px] font-semibold text-text-primary"><CircleDollarSign className="h-3.5 w-3.5 text-text-tertiary" />{formatCurrency(opportunity.amount)}</span><span className="rounded-full bg-accent-subtle px-2 py-0.5 text-[11px] font-semibold text-accent">{opportunity.probability}%</span></div>
    <div className="mt-2.5 flex items-center justify-between gap-2 text-[11px] text-text-tertiary"><span className="inline-flex min-w-0 items-center gap-1 truncate"><UserRound className="h-3.5 w-3.5 shrink-0" />{opportunity.owner.firstName} {opportunity.owner.lastName}</span>{opportunity.expectedCloseDate && <span className="inline-flex shrink-0 items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />{opportunity.expectedCloseDate.slice(0, 10)}</span>}</div>
  </motion.article>;
}

function Column({ stage, opportunities, draggable, isDropTarget, activeId, onCard }: { stage: PipelineStage; opportunities: ManagedOpportunity[]; draggable: boolean; isDropTarget: boolean; activeId: number | null; onCard: (o: ManagedOpportunity) => void }) {
  const drop = useDroppable({ id: `stage:${stage.id}` }); const total = opportunities.reduce((sum, item) => sum + item.amount, 0);
  return <section ref={drop.setNodeRef} className={cn('flex h-[min(64vh,650px)] min-h-[360px] w-[278px] shrink-0 flex-col rounded-2xl border bg-surface-secondary/45 transition-colors duration-150 sm:w-[292px]', isDropTarget ? 'border-accent/50 bg-accent-subtle/35 ring-2 ring-accent/15' : 'border-border')}>
    <header className="border-b border-border/80 px-3.5 py-3"><div className="flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: stage.color ?? 'var(--color-accent)' }} /><h2 className="truncate text-[13px] font-semibold text-text-primary">{stage.name}</h2></div><span className="rounded-md bg-background-tertiary px-1.5 py-0.5 text-[11px] font-medium text-text-secondary">{opportunities.length}</span></div><div className="mt-1.5 flex items-center justify-between"><p className="text-[11px] text-text-tertiary">{opportunities.length === 1 ? '1 opportunité' : `${opportunities.length} opportunités`}</p><p className="text-[12px] font-semibold text-text-secondary">{formatCurrency(total)}</p></div></header>
    <div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-2.5">{opportunities.map((item) => <Card key={item.id} opportunity={item} draggable={draggable} dragging={activeId === item.id} onClick={() => onCard(item)} />)}{!opportunities.length && <div className={cn('flex min-h-[116px] flex-col items-center justify-center rounded-xl border border-dashed px-4 text-center transition-colors', isDropTarget ? 'border-accent/50 bg-accent-subtle/35' : 'border-border/80 bg-surface/40')}><FilePlus2 className="mb-2 h-4 w-4 text-text-tertiary" /><p className="text-[12px] font-medium text-text-secondary">Aucune opportunité</p><p className="mt-1 text-[11px] leading-4 text-text-tertiary">Déplacez ou créez une opportunité dans cette étape.</p></div>}</div>
  </section>;
}

export function RealPipelineBoard({ board, canMove, onMove, onCard }: { board: PipelineBoardData; canMove: boolean; onMove: (opportunityId: number, stageId: number) => void; onCard: (o: ManagedOpportunity) => void }) {
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor)); const [activeId, setActiveId] = useState<number | null>(null); const [overStage, setOverStage] = useState<number | null>(null);
  const over = (event: DragOverEvent) => setOverStage(event.over && String(event.over.id).startsWith('stage:') ? Number(String(event.over.id).slice(6)) : null);
  const end = (event: DragEndEvent) => { const active = String(event.active.id); const target = event.over ? String(event.over.id) : ''; setActiveId(null); setOverStage(null); if (!target.startsWith('stage:') || !active.startsWith('opportunity:')) return; const opportunityId = Number(active.slice(12)); const stageId = Number(target.slice(6)); if (board.opportunities.find((item) => item.id === opportunityId)?.stage?.id !== stageId) onMove(opportunityId, stageId); };
  return <div className="rounded-2xl border border-border bg-surface p-2 shadow-xs"><DndContext sensors={sensors} collisionDetection={closestCorners} onDragStart={(event) => setActiveId(Number(String(event.active.id).slice(12)))} onDragOver={over} onDragCancel={() => { setActiveId(null); setOverStage(null); }} onDragEnd={end}><div className="pipeline-scrollbar flex gap-3 overflow-x-auto overscroll-x-contain px-1 pb-3 pt-1 sm:gap-4">{board.stages.map((stage) => <Column key={stage.id} stage={stage} opportunities={board.opportunities.filter((item) => item.stage?.id === stage.id)} draggable={canMove} isDropTarget={overStage === stage.id} activeId={activeId} onCard={onCard} />)}</div></DndContext><p className="px-2 pb-1 text-[11px] text-text-tertiary">Faites défiler horizontalement pour parcourir toutes les étapes.</p></div>;
}
