import {
  LayoutDashboard,
  Users,
  Building2,
  Target,
  GitBranch,
  Calendar,
  BarChart3,
  Bell,
  Settings,
  Sparkles,
  Search,
  Plus,
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  MoreHorizontal,
  Menu,
  Sun,
  Moon,
  Download,
  LogOut,
  User,
  UserCog,
  Mail,
  Phone,
  Inbox,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Info,
  Loader2,
  Eye,
  EyeOff,
  Pencil,
  Trash2,
  Filter,
  ArrowUpDown,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  FileText,
  File,
  Clock,
  GitCommit,
  Activity,
  UserCheck,
  Handshake,
  FileSignature,
  XCircle,
  GripVertical,
  ExternalLink,
  History,
  Tag,
  DollarSign,
  Percent,
  PieChart,
  List,
  Columns,
  MapPin,
  MessageSquare,
  Monitor,
  Coffee,
  Circle,
  CalendarDays,
  Flag,
  type LucideIcon,
} from 'lucide-react';

/**
 * Registre centralisé des icônes du projet.
 *
 * Toujours importer les icônes depuis ce fichier plutôt que directement
 * depuis `lucide-react` dans les composants métier : ça garde un
 * inventaire unique et explicite de l'iconographie utilisée par LeadPro
 * CRM, et facilite un remplacement de librairie d'icônes si besoin un
 * jour.
 */
export const Icons = {
  // Navigation / modules
  dashboard: LayoutDashboard,
  leads: Target,
  contacts: Users,
  companies: Building2,
  opportunities: GitBranch,
  calendar: Calendar,
  reports: BarChart3,
  barChart3: BarChart3,
  notifications: Bell,
  settings: Settings,
  aiAssistant: Sparkles,

  // Actions
  search: Search,
  add: Plus,
  close: X,
  check: Check,
  edit: Pencil,
  delete: Trash2,
  filter: Filter,
  sort: ArrowUpDown,
  refresh: RefreshCw,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  note: FileText,
  file: File,
  clock: Clock,
  statusChange: GitCommit,
  logout: LogOut,

  // Navigation UI
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  more: MoreHorizontal,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  export: Download,

  // Entités / contact
  user: User,
  account: UserCog,
  mail: Mail,
  phone: Phone,

  // Pipeline / Kanban
  activity: Activity,
  userCheck: UserCheck,
  handshake: Handshake,
  fileSignature: FileSignature,
  checkCircle2: CheckCircle2,
  xCircle: XCircle,
  gripVertical: GripVertical,
  externalLink: ExternalLink,
  history: History,
  tag: Tag,
  dollarSign: DollarSign,
  percent: Percent,
  pieChart: PieChart,
  list: List,
  columns: Columns,

  // Calendar / Tasks
  mapPin: MapPin,
  messageSquare: MessageSquare,
  monitor: Monitor,
  coffee: Coffee,
  circle: Circle,
  calendarDays: CalendarDays,
  flag: Flag,

  // États / feedback
  empty: Inbox,
  warning: AlertTriangle,
  alertTriangle: AlertTriangle,
  success: CheckCircle2,
  danger: AlertCircle,
  info: Info,
  spinner: Loader2,
  show: Eye,
  hide: EyeOff,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
